package server

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"bletonfc/vscode_tasks_menu/internal/tasks"
)

const taskDeckBashIntegrationRC = "# Generated by TaskDeck. Do not edit; this file may be replaced.\n" +
	"if [ -r \"$HOME/.bashrc\" ]; then\n" +
	"  . \"$HOME/.bashrc\"\n" +
	"fi\n\n" +
	"__taskdeck_emit_osc7() {\n" +
	"  printf '\\033]7;file://%s%s\\007' \"${HOSTNAME:-localhost}\" \"$PWD\"\n" +
	"}\n\n" +
	"__taskdeck_prompt_marker() {\n" +
	"  local __taskdeck_status=$?\n" +
	"  if [ \"${__TASKDECK_PROMPT_SEEN:-0}\" = \"1\" ]; then\n" +
	"    printf '\\033]133;D;%d\\007' \"$__taskdeck_status\"\n" +
	"  fi\n" +
	"  __TASKDECK_PROMPT_SEEN=1\n" +
	"  __taskdeck_emit_osc7\n" +
	"  printf '\\033]133;A\\007'\n" +
	"  return \"$__taskdeck_status\"\n" +
	"}\n\n" +
	"case \"${PROMPT_COMMAND:-}\" in\n" +
	"  *__taskdeck_prompt_marker*) ;;\n" +
	"  '') PROMPT_COMMAND='__taskdeck_prompt_marker' ;;\n" +
	"  *) PROMPT_COMMAND='__taskdeck_prompt_marker;'\"$PROMPT_COMMAND\" ;;\n" +
	"esac\n\n" +
	"if [ -z \"${PS1:-}\" ]; then PS1='\\u@\\h:\\w\\$ '; fi\n" +
	"case \"${PS1:-}\" in\n" +
	"  *']133;B'*) ;;\n" +
	"  *) PS1=\"${PS1}\"'\\[\\033]133;B\\007\\]' ;;\n" +
	"esac\n\n" +
	// Bash 4.4+ exposes PS0: expanded only after a complete command line
	// has been accepted and just before its execution (not while idle).
	"if [ \"${BASH_VERSINFO[0]:-0}\" -gt 4 ] || { [ \"${BASH_VERSINFO[0]:-0}\" -eq 4 ] && [ \"${BASH_VERSINFO[1]:-0}\" -ge 4 ]; }; then\n" +
	"  case \"${PS0:-}\" in\n" +
	"    *']133;C'*) ;;\n" +
	"    *) PS0='\\033]133;C\\007'\"${PS0:-}\" ;;\n" +
	"  esac\n" +
	"fi\n"

// The normal SSH login shell sources /etc/profile and the first Bash login
// profile before showing a prompt. Remote commands entered through ssh -tt
// are not login shells, so emulate that initialization in the temporary RC.
// Do not source ~/.bashrc a second time if the login profile already did it.
func taskDeckSSHLoginBashRC() string {
	const localPrelude = "# Generated by TaskDeck. Do not edit; this file may be replaced.\n" +
		"if [ -r \"$HOME/.bashrc\" ]; then\n" +
		"  . \"$HOME/.bashrc\"\n" +
		"fi\n\n"
	const remotePrelude = "# Generated by TaskDeck. Ephemeral SSH shell integration.\n" +
		"if [ -r /etc/profile ]; then . /etc/profile; fi\n" +
		"if [ -r \"$HOME/.bash_profile\" ]; then\n" +
		"  . \"$HOME/.bash_profile\"\n" +
		"elif [ -r \"$HOME/.bash_login\" ]; then\n" +
		"  . \"$HOME/.bash_login\"\n" +
		"elif [ -r \"$HOME/.profile\" ]; then\n" +
		"  . \"$HOME/.profile\"\n" +
		"fi\n\n"
	return strings.Replace(taskDeckBashIntegrationRC, localPrelude, remotePrelude, 1)
}

func ensureTaskDeckBashIntegrationRC() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(configDir, "vscode_tasks_menu", "shell")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "taskdeck-bashrc")
	current, readErr := os.ReadFile(path)
	if readErr == nil && string(current) == taskDeckBashIntegrationRC {
		return path, nil
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(taskDeckBashIntegrationRC), 0o600); err != nil {
		return "", err
	}
	if err := os.Chmod(tmp, 0o600); err != nil {
		_ = os.Remove(tmp)
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return "", err
	}
	return path, nil
}

func configureTerminalShellIntegration(spec *tasks.Execution) error {
	if spec == nil {
		return fmt.Errorf("terminal execution is nil")
	}
	if strings.EqualFold(filepath.Base(spec.Command), "bash") {
		rc, err := ensureTaskDeckBashIntegrationRC()
		if err != nil {
			return err
		}
		spec.Args = []string{"--rcfile", rc, "-i"}
		spec.Preview = spec.Command + " --rcfile " + rc + " -i"
	}
	return nil
}
